const HTTP_STATUS_ERROR_NOT_FOUND = "404";
const HTTP_STATUS_ERROR_QUERY = "400";
const HTTP_STATUS_ERROR_UNKNOWN = "500";

exports.HTTP_STATUS_ERROR_NOT_FOUND = HTTP_STATUS_ERROR_NOT_FOUND;
exports.HTTP_STATUS_ERROR_QUERY = HTTP_STATUS_ERROR_QUERY;
exports.HTTP_STATUS_ERROR_UNKNOWN = HTTP_STATUS_ERROR_UNKNOWN;
